services:
  mongo:
    image: mongo:7.0
    container_name: lets-play-mongo
    restart: on-failure:3
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: letsplay
    volumes:
      - ./docker-data/mongodb:/data/db
